# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

# /// To determine the status of a particular data sample
class DataStatus(object):
    speculative = 0
    committed = 1
    invalid = 2

