# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

# /// To identify what instrumentation mode the data comes from
class InstMode(object):
    none = 0
    GVT = 1
    VT = 2
    RT = 3
    ET = 4

