# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

import flatbuffers

class IntVar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntVar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntVar()
        x.Init(buf, n + offset)
        return x

    # IntVar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntVar
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntVar
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # IntVar
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def IntVarStart(builder): builder.StartObject(1)
def IntVarAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def IntVarStartValueVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IntVarEnd(builder): return builder.EndObject()
