# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

import flatbuffers

class LongVar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLongVar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LongVar()
        x.Init(buf, n + offset)
        return x

    # LongVar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LongVar
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # LongVar
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # LongVar
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LongVarStart(builder): builder.StartObject(1)
def LongVarAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def LongVarStartValueVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def LongVarEnd(builder): return builder.EndObject()
