# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

import flatbuffers

class PEData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPEData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PEData()
        x.Init(buf, n + offset)
        return x

    # PEData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PEData
    def Peid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PEData
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .SimEngineMetrics import SimEngineMetrics
            obj = SimEngineMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PEDataStart(builder): builder.StartObject(2)
def PEDataAddPeid(builder, peid): builder.PrependInt32Slot(0, peid, 0)
def PEDataAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def PEDataEnd(builder): return builder.EndObject()
