# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

# /// To be used by model metrics
class VariableType(object):
    NONE = 0
    IntVar = 1
    LongVar = 2
    FloatVar = 3
    DoubleVar = 4

